# This is a sample configuration file for pipeline construction
#
# bin/parse.js, bin/parserTests.js, bin/roundtrip-test.js all accept
# the --phpConfigFile <file> option on the commandline to pass in
# a config file such as this.

wt2html:
   # Supported, but this needs better mocking support
   PegTokenizer: false

   # Note that this implicitly runs all the transformers
   # registered for stage 1 (in parser.js) on the PHP side
   # This would be:
   # - NoInclude
   # - IncludeOnly
   # - OnlyInclude
   SyncTokenTransformManager1: false

   # --- NOT YET SUPPORTED ---
   # Note that this implicitly runs all the transformers
   # registered for stage 2 (in parser.js) on the PHP side
   # This would be:
   # - WikiLinkHandler
   # - ExternalLinkHandler
   # - ExtensionHandler
   # - DOMFragmentBuilder
   # - AttributeExpander
   # - LanguageVariantHandler
   # - TemplateHandler
   SyncTokenTransformManager2: false

   # Note that this implicitly runs all the transformers
   # registered for stage 3 (in parser.js) on the PHP side
   # These would be:
   # - TokenStreamPatcher
   # - PreHandler
   # - QuoteTransformer
   # - BehaviorSwitchHandler
   # - ListHandler
   # - SanitizerHandler
   # - ParagraphWrapper
   SyncTokenTransformManager3: false

   # Builds initial DOM from parsed tokens
   HTML5TreeBuilder: false

   # Note that this implicitly runs all the DOM transformers
   # on the PHP side
   DOMPostProcessor: false

   TT:
     ParagraphWrapper: false
     QuoteTransformer: false
     PreHandler: false
     ListHandler: false
     # Supported, but this needs better mocking support
     BehaviorSwitchHandler: false
     NoInclude: false
     IncludeOnly: false
     OnlyInclude: false
     SanitizerHandler: false

     # The following handlers aren't yet supported
     # As the associated code is ported, they will get
     # supported one at a time
     WikiLinkHandler: false
     ExternalLinkHandler: false
     ExtensionHandler: false
     DOMFragmentBuilder: false
     AttributeExpander: false
     LanguageVariantHandler: false
     TemplateHandler: false
   DOM:
     # Processors that provide their own DOM Traversal
     AddMediaInfo: false
     PWrap: false
     ProcessTreeBuilderFixups: false
     AddRedLinks: false
     MarkFosteredContent: false
     ComputeDSR: false
     Linter: false
     WrapSections: false
     WrapTemplates: false
     HandlePres: false
     AddExtLinkClasses: false

     # Handlers that run in a DOMTraverser
     # - Running many of these will require dirtying DOMPostProcessor.js locally
     #   to unbundle them to their own DOMTraverser (since by default, many are
     #   bundled with other handlers in the same traversal for efficiency reasons)
     TableFixups: false
     HandleLinkNeighbours: false
     UnpackDOMFragments: false
     LiFixups: false
     DedupeStyles: false
     Headings-genAnchors: false
     Headings-dedupeHeadingIds: false
     CleanUp-stripMarkerMetas: false
     CleanUp-handleEmptyElts: false
     CleanUp-cleanupAndSaveDataParsoid: false

html2wt:
  # This implicitly enables both serializers as well as dom diff and dom normalizer
  Serializer: false
  DOMDiff: false
  DOMNormalizer: false

# This is not yet supported
exts:
  Cite: false
  Poem: false
