# This is a sample configuration file for pipeline construction
#
# bin/parse.js, bin/parserTests.js, bin/roundtrip-test.js all accept
# the --phpConfigFile <file> option on the commandline to pass in
# a config file such as this.

wt2html:
   # Supported, but this needs better mocking support
   PegTokenizer: false
   HTML5TreeBuilder: false

   # Note that this implicitly runs all the transformers
   # registered for stage 1 (in parser.js) on the PHP side
   # This would be:
   # - NoInclude
   # - IncludeOnly
   # - OnlyInclude
   SyncTokenTransformManager1: false

   # Note that this implicitly runs all the transformers
   # registered for stage 2 (in parser.js) on the PHP side
   # These would be:
   # - TokenStreamPatcher (not yet ported)
   # - PreHandler
   # - QuoteTransformer
   # - BehaviorSwitchHandler (needs better Env support)
   # - ListHandler
   # - SanitizerHandler (being ported, not yet merged)
   # - ParagraphWrapper
   SyncTokenTransformManager2: false

   TT:
     ParagraphWrapper: false
     QuoteTransformer: false
     PreHandler: false
     ListHandler: false
     # Supported, but this needs better mocking support
     BehaviorSwitchHandler: false
     NoInclude: false
     IncludeOnly: false
     OnlyInclude: false
     SanitizerHandler: false
   DOM:
     PWrap: false
     ComputeDSR: false
     WrapSections: false
     HandlePres: false
     AddExtLinkClasses: false
     TableFixups: false

html2wt:
  DOMDiff: false
  DOMNormalizer: false

# This is not yet supported
exts:
  Cite: false
  Poem: false
