# This is a sample configuration file for pipeline construction
#
# bin/parse.js, bin/parserTests.js, bin/roundtrip-test.js all accept
# the --phpConfigFile <file> option on the commandline to pass in
# a config file such as this.

wt2html:
   Tokenizer: false
   TT:
     ParagraphWrapper: false
     QuoteTransformer: false
     PreHandler: false
     ListHandler: false
   DOM:
     PWrap: false
     ComputeDSR: false
     WrapSections: false

html2wt:
  DOMDiff: false
  DOMNormalizer: false

exts:
  Cite: false
  Poem: false
